export const volunteerType = {
  firstName: "",
  lastName: "",
  email: "",
  gender: "",
  isMember: null,
  isServing: null,
  yearJoined: "",
  department: [],
  contactNumber: "",
  whatsAppNumber: "",
  ageRange: "",
  medicalCondition: "",
  isMedicalPractitioner: null,
  canLiftHeavyObjects: null,
  canTakeWeekfOff: null,
  daysAvailable: [],
  preferredTeam: "",
  mediaAbilities: [],
};
